sudo: required
language: python
python:
- '3.5'
- '3.6'
before_install:
- pushd /usr/lib/x86_64-linux-gnu/ && sudo ln -s libboost_python-py34.so libboost_python3.so
  && popd
install:
- pip install flit
- flit install
- flit build
script: pytest
deploy:
- provider: pypi
  user: mehdix
  password:
    secure: pbVLSvAlnvYYJljBYJAmvp/h7IGFlkG7X9Bkr3KHHmr8z8i2uN4Ru45cjsZHDhyN7sFmjrzKZL1P4tiTKji52U0xHTy2Utq9YzgIuhIRBtg+1KOZY9KkTGPmNyBViW4fyBz3WPICplWabl7mJrkx9enCAY0XbDNYyNpdLlTYhC0Spp+wD2iznIFnnzJWDuN9uuAoNXEQbjAQoi9d1g+Vngb694vRJ9C25hG0Ek7jk3Ff9KEkppQsIVk1P+Pwm8dhBTNPrYwr5qo1J7uTP+dwP6uuQH5Uwpe+f3RjZ9ZnDK6wmrv8IpCdt4Yerm3+dfJKobY1L9QPg9+OTmo3VgBOdsCMlx6CSnX/zy7v3FPU5wKAZuxkkmU4Eh98pCjLbdU1Brn4J3vG3fMfnpQzOD2tBCpJd6NzEMEKWgW/7QffgItRC5DQRdwWLrsEVky/IyZ6uXGW2kFCGA6PSdkznkwzHKeVMlgirPnMQbEgfVPVpRihMcPc7oAKkYmqHG4MOTbJV1WPYxsXOzBW83nv5MfbP4h7Xf616t+18Za8GOPAKtHowGRHWrQJjIwPoSrREQSROMoERH4ax1CwV8mCA35/PZZk2mwl63q6u3WTUzj9e2dTu1VTlz5Ctx0nnKjvwoIpoXimOBM9bQjsjbK7TSKIrad4byyUQ83QyWkA155icF0=
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  on:
    tags: true
    python: 3.6
    branch: master
addons:
  apt:
    packages:
    - libosmium-dev
    - libboost-python-dev
